; Universidade Federal do Ceará
; Departamento de Engenharia Elétrica
; Disciplina : Microprocessadores
; Aluno : Thyago Freitas da Silva
; Parte I do Projeto de Laboratório
    
#INCLUDE <P16F628A.INC>

#DEFINE  MOTOR_ESQ  PORTB,0
#DEFINE  MOTOR_DIR  PORTB,1
#DEFINE	 SENSOR     PORTA,0
#DEFINE	 CHAVE      PORTA,1
    
CONT1   EQU 0X21
CONT2   EQU 0X22
CONT3   EQU 0X23

ORG     0x00
    GOTO    INI

ORG     0x04
    RETFIE
    
INI:
  ; DESLIGANDO MODULO COMPARADOR 
    BANKSEL CMCON
    MOVLW   0x07
    MOVWF   CMCON
    
  ; CONFIGURANDO PORTA COMO INPUT ATRAVES DO REGISTRADOR TRISA
    BANKSEL TRISA
    MOVLW   0xFF
    MOVWF   TRISA
    
  ; CONFIGURANDO PORTB COMO OUTPUT ATRAVES DO REGISTRADOR TRISB
    BANKSEL TRISB
    MOVLW   0x00
    MOVWF   TRISB
    
  ; CONFIGURANDO PWM : DUTY_CYCLE = 80%,Fosc = 10MHz, Fpwm = 4.88KHz
    BANKSEL CCP1CON
    MOVLW   B'00101100'
    MOVWF   CCP1CON

    BANKSEL PR2
    MOVLW   D'127'
    MOVWF   PR2
    
    BANKSEL T2CON
    MOVLW   B'00000101'	
    MOVWF   T2CON

    BANKSEL CCPR1L
    MOVLW   B'01100110'
    MOVWF   CCPR1L
    
  ; CONFIGURAÇAO INICIAL DOS MOTORES = ATIVO
    BANKSEL PORTB
    BCF	    MOTOR_ESQ
    BCF	    MOTOR_DIR

MAIN:
    BTFSC   SENSOR          ; SE FOR 1, QUER DIZER QUE A CURVA FOI DETECTADA.
    CALL    ANALISE_CURVA
    GOTO    MAIN    

ANALISE_CURVA:
    BTFSC   CHAVE
    CALL    CURVA_DIREITA
    BTFSS   CHAVE
    CALL    CURVA_ESQUERDA
    RETURN

CURVA_DIREITA:
    BSF	    MOTOR_DIR
    CALL    DELAY
    BCF	    MOTOR_DIR
    RETURN
    
CURVA_ESQUERDA:
    BSF	    MOTOR_ESQ
    CALL    DELAY
    BCF	    MOTOR_ESQ
    RETURN

DELAY:
    MOVLW 0X6D
    MOVWF CONT1
    MOVLW 0X5E
    MOVWF CONT2
    MOVLW 0X1A
    MOVWF CONT3
    LOOP
    DECFSZ CONT1, 1
    GOTO LOOP
    DECFSZ CONT2, 1
    GOTO LOOP
    DECFSZ CONT3, 1
    GOTO LOOP
    RETURN

END