ORG 100h
W EQU 30
H EQU 30

MOV AH,0
MOV AL,13h
INT 10h

MOV CX,100+W     ; CX = 130 -> COLUNA DO PIXEL
MOV DX,20+H      ; DX = 130 -> LINHA DO PIXEL

MOV AL,3         ; AL = 3,COR DO PIXEL

parte1:
    parte2:
    MOV AH,0ch   ; INTERRUPCAO PARA PINTAR UM PIXEL, AL = COR
    INT 10h      ; INTERRUPCAO PARA PINTAR UM PIXEL, AL = COR
    MOV AH,6     ; CONFIGURANDO PARA TER A INTERRUPCAO DE ENTRADA OU SAIDA
    MOV BL,DL    ; SALVANDO O VALOR DE DL EM BL (LINHA DO PIXEL)
    MOV BH,AL    ; SALVANDO O VALOR DE AL EM BH (COR DO PIXEL)
    MOV DL,255   ; CONFIGURANDO A INTERRUPCAO PARA SER DE LEITURA
    INT 21h      ; O QUE FOR LIDO SERA SALVO EM AL
    CMP AL,120   ; SE AL = 120(NUMERO QUE REPRESENTA O "X" NA TABELA ASC)
    JNE corAtual ; SE NAO FOR IGUAL X,VAI PRA CONTINUA
    JMP mudaCor  ; SE FOR IGUAL,TA NA HORA DE TROCAR A COR
    
    corAtual:
    MOV AL,BH
    JMP CONTINUA
    
    mudaCor:     ; INCREMENTA EM 1 A COR ANTIGA
    MOV AL,BH
    INC AL 
    
    continua:    ; INDEPENDENTE DE TER TROCADO COR OU NAO,CONTINUA
    MOV DL,BL    ; RESGATA A LINHA
    DEC CX       ; DECREMETA CX (130,129,128...)
    CMP CX,100   ; CX = 100 OU NAO
    JAE parte2   ; SE CX >= 100,PULA PRA PARTE2
    MOV CX,100+W ; SE NAO FOR,CX = 130,
    DEC DX       ; DECREMENTA A LINHA(DX = 50,49...20)
    CMP DX,20    ; DX >= 20,SE FOR PULA PRA PARTE 1
    JAE parte1
    MOV AH,00    ;
    INT 16h
    MOV AH,0
    MOV AL,13h
    INT 10h
    RET

END